# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcontact.proto\"\x18\n\tClientMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x19\n\tServerMsg\x12\x0c\n\x04task\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x15\n\x06Result\x12\x0b\n\x03ret\x18\x01 \x01(\t2r\n\x07\x43ontact\x12%\n\nsendStatus\x12\n.ClientMsg\x1a\x07.Result(\x01\x30\x01\x12\x1f\n\x07getTask\x12\x06.Empty\x1a\n.ServerMsg0\x01\x12\x1f\n\ntellResult\x12\x07.Result\x1a\x06.Empty(\x01\x62\x06proto3'
)




_CLIENTMSG = _descriptor.Descriptor(
  name='ClientMsg',
  full_name='ClientMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ClientMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=41,
)


_SERVERMSG = _descriptor.Descriptor(
  name='ServerMsg',
  full_name='ServerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='ServerMsg.task', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=68,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=77,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Result.ret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['ClientMsg'] = _CLIENTMSG
DESCRIPTOR.message_types_by_name['ServerMsg'] = _SERVERMSG
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientMsg = _reflection.GeneratedProtocolMessageType('ClientMsg', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMSG,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:ClientMsg)
  })
_sym_db.RegisterMessage(ClientMsg)

ServerMsg = _reflection.GeneratedProtocolMessageType('ServerMsg', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMSG,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:ServerMsg)
  })
_sym_db.RegisterMessage(ServerMsg)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)



_CONTACT = _descriptor.ServiceDescriptor(
  name='Contact',
  full_name='Contact',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=102,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendStatus',
    full_name='Contact.sendStatus',
    index=0,
    containing_service=None,
    input_type=_CLIENTMSG,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTask',
    full_name='Contact.getTask',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVERMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='tellResult',
    full_name='Contact.tellResult',
    index=2,
    containing_service=None,
    input_type=_RESULT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTACT)

DESCRIPTOR.services_by_name['Contact'] = _CONTACT

# @@protoc_insertion_point(module_scope)
